#!/bin/sh

set -e

if [ -z "$RELIQUARY" ]; then
	RELIQUARY=$HOME/.config/reliquary
fi

DIR=$RELIQUARY
API=`cat $DIR/api`
TOKEN=`cat $DIR/token`

if [ $# -ne 1 ]; then
	echo "Usage: reliquary-flock-delete flock"

	echo ""
	echo "This deletes a flock and all underlying devices."

	exit 1
fi

resp=`curl -s --show-error --fail -H "x-token: $TOKEN" --data "" $API/flock/$1/delete`

if [ $? -eq 0 ]; then
	echo "$resp"
else
	echo "something went wrong: $resp"
fi
