#!/bin/sh

set -e

if [ -z "$RELIQUARY" ]; then
	RELIQUARY=$HOME/.config/reliquary
fi

DIR=$RELIQUARY

if [ $# -ne 3 ] ; then
	echo "Usage: reliquary-kek-install flock kek-id /path/to/kek"

	echo ""
	echo "Install the KEK given by the path into the specified flock."
	echo "After doing so the device is ready to be used."
	echo ""

	exit 1
fi

if [ -f $DIR/$1/device_kek ]; then
	echo "A KEK already seems to be installed for $1"
	exit 1
fi

cp $3 $DIR/$1/kek-0x$2
echo $2 > $DIR/$1/device_kek

echo "The KEK is now installed as kek-0x$2 in $1."
