#!/bin/sh

set -e

if [ -z "$RELIQUARY" ]; then
	RELIQUARY=$HOME/.config/reliquary
fi

DIR=$RELIQUARY

if [ $# -ne 2 ]; then
	echo "Usage: reliquary-login [api] [account-key]"
	echo ""
	echo "Login to the reliquary specified by the given api and"
	echo "your account key."
	echo ""
	echo "When doing a login for the first time this script will setup"
	echo "the required directories under $HOME/.config/reliquary."
	echo ""

	exit 1
fi

resp=`curl -s --show-error --fail --data "$2" $1/init`

if [ $? -eq 0 ]; then
	token=`echo $resp | jq -r .token`
	natport=`echo $resp | jq -r .natport`
	cathedral=`echo $resp | jq -r .cathedral`

	mkdir -p $DIR
	echo $1 > $DIR/api
	echo $token > $DIR/token
	echo $natport > $DIR/natport
	echo $cathedral > $DIR/cathedral

	echo "reliquary initialised"
else
	echo "something went wrong: $token"
fi
