#!/bin/sh

set -e

if ! command -v jq > /dev/null 2>&1; then
	echo "jq dependency missing";
	exit;
fi

if ! command -v xxd > /dev/null 2>&1; then
	echo "xxd dependency missing";
	exit;
fi

if ! command -v curl > /dev/null 2>&1; then
	echo "curl dependency missing";
	exit;
fi

if [ -z "$RELIQUARY" ]; then
	RELIQUARY=$HOME/.config/reliquary
fi

DIR=$RELIQUARY

if [ $# -ne 1 ]; then
	echo "Usage: reliquary-init [api]"
	echo ""
	echo "Initialises the reliquary repository using the given api."
	echo ""

	exit 1
fi

resp=`curl -s --show-error --fail --data "" $1/init`

if [ $? -eq 0 ]; then
	natport=`echo $resp | jq -r .natport`
	cathedral=`echo $resp | jq -r .cathedral`

	mkdir -p $DIR
	touch $DIR/token
	echo $1 > $DIR/api
	echo $natport > $DIR/natport
	echo $cathedral > $DIR/cathedral

	echo "reliquary initialised"
else
	echo "something went wrong: $token"
fi
