#!/bin/sh

set -e

if [ -z "$RELIQUARY" ]; then
	RELIQUARY=$HOME/.config/reliquary
fi

DIR=$RELIQUARY

API=`cat $DIR/api`
TOKEN=`cat $DIR/token`

if [ $# -ne 3 ]; then
	echo "Usage: reliquary-xflock-ambry flock_a flock_b /path/to/ambry"
	echo ""
	echo "This is the cross-flock variant of reliquary-ambry-upload."
	echo ""
	echo "Upload an Ambry bundle to the servers for distribution"
	echo "to all of your devices."
	echo ""
	echo "This Ambry bundle contains KEK-wrapped shared secrets"
	echo "for your tunnels. The cathedrals cannot read, nor modify these."

	exit 1
fi

if [ ! -f $3 ]; then
	echo "The bundle '$3' is not a file or does not exist"
	exit 1
fi

resp=`curl -s --show-error --fail -H "x-token: $TOKEN" --data-binary @$3 $API/xflock/$1/$2/ambry`

if [ $? -eq 0 ]; then
	echo $resp
else
	echo "something went wrong"
fi

