---
- name: Restart cathedral services
  hosts: cathedrals
  become: true

  tasks:
  - name: Restarting cathedral
    ansible.builtin.service:
      name: cathedral.service
      state: restarted

  - name: Restarting cathedral (legacy)
    ansible.builtin.service:
      name: cathedral-legacy.service
      state: restarted
